services:
  pma:
    image: phpmyadmin:5.2.1
    container_name: onl-pma
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 500M
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 127.0.0.1:${PMA_PORT}:80
    restart: unless-stopped
